services:
  backend:
    build: ./backend
    container_name: fastaxi-backend
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    volumes:
      - ./backend:/backend
    ports:
      - "8080:3000" 

  frontend:
    build: ./frontend
    container_name: fastaxi-frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:5173" 