services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:3000"  # Porta do host: 8080 -> Porta do contêiner: 3000
    volumes:
      - ./backend:/backend


  frontend:
    build:
      context: ./frontend
    ports:
      - "80:5173"  # Porta do host: 80 -> Porta do contêiner: 5173
    volumes:
      - ./frontend:/frontend