services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastaxi-backend
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "8080:3000" 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fastaxi-frontend
    ports:
      - "80:5173" 